# Generated by Django 5.0.4 on 2024-05-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Band",
            new_name="Player",
        ),
    ]
