# Generated by Django 5.0.4 on 2024-05-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_rename_band_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
    ]
