# Generated by Django 5.0.4 on 2024-05-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_listing"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Listing",
            new_name="Games",
        ),
    ]
