# Generated by Django 5.0.4 on 2024-05-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_rename_listing_games"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Games",
            new_name="Game",
        ),
    ]
