# Generated by Django 5.0.4 on 2024-05-09 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_rename_games_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="player",
            name="biography",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="birth_year",
            field=models.IntegerField(
                default=2000,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2024),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="genre",
            field=models.CharField(
                choices=[
                    ("HH", "Hip Hop"),
                    ("SP", "Synth Pop"),
                    ("AR", "Alternative Rock"),
                ],
                default="HH",
                max_length=5,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="official_homepage",
            field=models.URLField(blank=True, null=True),
        ),
    ]
