# Generated by Django 5.0.4 on 2024-05-09 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_player_active_player_biography_player_birth_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="description",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="type",
            field=models.CharField(
                choices=[("AD", "Adventure"), ("SP", "Sport"), ("PU", "Puzzle")],
                default="AD",
                max_length=5,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="year",
            field=models.IntegerField(
                default=2023,
                validators=[
                    django.core.validators.MinValueValidator(2023),
                    django.core.validators.MaxValueValidator(2024),
                ],
            ),
            preserve_default=False,
        ),
    ]
