# Generated by Django 5.0.4 on 2024-05-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_game_description_game_sold_game_type_game_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="creator",
            field=models.CharField(
                choices=[("BV", "Ben"), ("VV", "Victor"), ("KR", "Kenneth")],
                default="BV",
                max_length=5,
            ),
            preserve_default=False,
        ),
    ]
