# Generated by Django 5.0.4 on 2024-05-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_alter_game_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="creator",
        ),
    ]
