# Generated by Django 5.0.4 on 2024-05-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0011_game_creator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="creator",
            new_name="player",
        ),
    ]
