# Generated by Django 5.0.4 on 2024-05-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0012_rename_creator_game_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="creator",
            field=models.CharField(
                choices=[("BV", "Ben"), ("VV", "Victor"), ("KR", "Kenneth")],
                default="BV",
                max_length=5,
            ),
            preserve_default=False,
        ),
    ]
