# Generated by Django 5.0.4 on 2024-05-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0014_remove_game_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="like_new",
            field=models.BooleanField(default=False),
        ),
    ]
