# Generated by Django 5.0.4 on 2024-05-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0015_game_like_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="like_new",
        ),
    ]
